<?php

declare(strict_types=1);

final class GBDBWeek90To103Quality {
    private array $results = [];
    private string $instance;
    private string $base = 'week90_103_quality';
    private string $table = 'items';

    public function __construct() { $this->instance = 'test_w90_103_' . substr(hash('sha1', (string)microtime(true)), 0, 8); }
    public function run(): array { $old = GBDB::getActualInstance(); try { GBDB::createInstance($this->instance); GBDB::setInstance($this->instance); $this->testMigrationUpdate(); $this->testShortApiCrud(); $this->testSearchAndPolicy(); $this->testBackupRestoreRepair(); $this->testQueueMediaCompatibility(); $this->testRenameAndScriptExecution(); } finally { GBDB::setInstance($old); } $ok = !in_array(false, array_column($this->results, 'ok'), true); return ['ok'=>$ok,'tests'=>$this->results,'count'=>count($this->results)]; }
    private function assert(string $name, bool $ok, mixed $details = null): void { $this->results[] = ['name'=>$name,'ok'=>$ok,'details'=>$details]; }
    private function testMigrationUpdate(): void { $report = GBDB::update(); $this->assert('migration_update_report', is_array($report) && array_key_exists('ok',$report), $report); $this->assert('versioned_instance_api', GBDB::getActualInstance() !== 'default', GBDB::getActualInstance()); }
    private function testShortApiCrud(): void { $this->assert('create_base_table', GBDB::create($this->base,$this->table,true,['title'=>'string','body'=>'text','created_at'=>'int'])); $id=GBDB::insert($this->base,$this->table,['title'=>'Alpha','body'=>'GBDB Woche 90 Test','created_at'=>time()]); $this->assert('insert_alias',$id>0,$id); $row=GBDB::get($this->base,$this->table,'id',$id); $this->assert('get_alias_by_id',is_array($row)&&($row['title']??'')==='Alpha',$row); $this->assert('edit_alias',GBDB::edit($this->base,$this->table,'id',$id,['title'=>'Beta'])); $this->assert('exists_alias',GBDB::exists($this->base,$this->table,'id',$id)); $this->assert('next_id_alias',GBDB::getNextId($this->base,$this->table)>$id); }
    private function testSearchAndPolicy(): void { $hits=GBDB::fullTextSearch($this->base,$this->table,'Woche 90'); $this->assert('full_text_search',count($hits)>=1,$hits); $this->assert('security_policy_methods_available',method_exists('GBDB','setPolicy')||method_exists('GBDB','adminLog')); }
    private function testBackupRestoreRepair(): void { $backupDir=sys_get_temp_dir().'/gbdb_week90_backup_'.substr(hash('sha1',(string)microtime(true)),0,8); $backup=GBDB::tableBackup($this->base,$this->table,$backupDir); $this->assert('backup_create',!empty($backup['ok'])&&is_dir($backupDir),$backup); $verify=GBDB::verifyBackup($backupDir); $this->assert('backup_verify',!empty($verify['ok']),$verify); $restore=GBDB::restoreTest($backupDir); $this->assert('restore_test',!empty($restore['ok']),$restore); $repair=method_exists('GBDB','integrityCheck')?GBDB::integrityCheck($this->base,$this->table):['ok'=>true,'note'=>'integrityCheck unavailable']; $this->assert('repair_integrity_entrypoint',is_array($repair),$repair); }
    private function testQueueMediaCompatibility(): void { $this->assert('queue_entrypoints',method_exists('GBDB','enqueueJob')||method_exists('GBDB','createQueue')); $this->assert('media_entrypoints',method_exists('GBDB','deleteMedia')||method_exists('GBDB','backgroundMediaProcessing')||method_exists('GBDB','mediaAudit')); }
    private function testRenameAndScriptExecution(): void { $this->assert('rename_table',GBDB::renameTable($this->base,$this->table,'items_renamed')); $this->assert('rename_base',GBDB::renameBase($this->base,'week90_103_quality_renamed')); $script=sys_get_temp_dir().'/gbdb_week90_script_'.substr(hash('sha1',(string)microtime(true)),0,8).'.gql'; file_put_contents($script,'OUTPUT "Woche 90-103";'); $result=GBDB::runFile($script); $this->assert('run_file_alias',is_array($result)&&array_key_exists('ok',$result),$result); @unlink($script); }
}
if (basename(__FILE__) === basename((string)($_SERVER['SCRIPT_FILENAME'] ?? ''))) { require_once dirname(__DIR__,3).'/gbdb.php'; header('Content-Type: application/json; charset=utf-8'); echo json_encode((new GBDBWeek90To103Quality())->run(), JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES); }
